# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool: myagent

variables:
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"
  solution: "**/WebApplication1.sln"
  project": "**/WebApplication1/WebApplication1.csproj"

steps:
- task: DotNetCoreCLI@2
  name: "build"
  displayName: "build the sln"
  inputs:
    command: 'build'
    projects: |
      $(project)
      $(solution)
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  name: "publish"
  displayName: "dot net publish"
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output  $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  name: "PublishBuildArtifacts"
  displayName: "Publish Build Artifacts"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drophere'
    publishLocation: 'Container'